### ISSUE TITLE
use naming-service to find solver images

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-refresh-job#16]
perfect use case for the naming service: https://github.com/thoth-station/graph-refresh-job/blob/0b786a9bcf06be8f1571da04725fc820f9a5d683/app.py#L51

**Comment by fridex** [comment]
What about using [custom resources](https://trello.com/c/XmxmtOyW/144-use-openshift-objects-as-a-template-for-analyzers-solvers-we-can-run) as discussed in the meeting?

**Comment by fridex** [comment]
This is implemented as a query to OpenShift respecting the label selector. Thus closing this issue.
