### ISSUE TITLE
Generated metrics

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-refresh-job#25]
Generate and export metrics per refresh job, provide them to Prometheus

**Comment by goern** [comment]
@pacospace is this done?

**Comment by pacospace** [comment]
Yes it is, through Pushgateway https://github.com/thoth-station/graph-refresh-job/blob/60e48344a9ca5e6a287c444379ab2ca68e8af2df/app.py#L67. What about changing it to Kafka App as for `package-update-job` and send message to Kafka? :D
