### ISSUE TITLE
Request to release tag for the application

### ISSUE THREAD

**Issue by harshad16** [thoth-station/graph-refresh-job#429]
I would like to have a new release for the application. However the confusion of what tag value to be used.
following are some details:
changelog: it only contains 0.4.0 and 0.3.0 info (however the info is incomplete).
tag: there is no tag present in the repository 
quay: v0.6.0-dev is present( unaware what commit message is it pointing)

idea:
- start from the beginning tag v0.1.0 with custom changelog
- use kebechet to pull up new tag v0.x.0 
- (undesired) i can lookup some commit message from previously from images to create v0.1.0-v0.6.0  
- others

@goern  @fridex  @pacospace  what should we do ?

**Comment by fridex** [comment]
I'm fine with starting from the beginning or using Kebechet to bump the version. We need to start somehow :)

**Comment by goern** [comment]
Let's use Kebechet
