### ISSUE TITLE
Schedule SI workflows for packages already stored in the database. [5pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/graph-refresh-job#430]
**Is your feature request related to a problem? Please describe.**
SI need to be collected for Python packages already in the database.

**Describe the solution you'd like**
Using thoth-storages methods to check the database and thoth-common methods to schedule workflows as we do for solvers. 

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
Can we create a new workflow that would encapsulate solvers and all the other data aggregation needed for a package (security indicators, ...)? The graph-refresh job can schedule just one workflow and argo can do all the remaining bits to have data aggregated (e.g. conditionally, retries, ...).

**Comment by fridex** [comment]
Scheduling security indicators for already known packages can be performed using a simple script, even from a local machine:

https://thoth-station.ninja/docs/developers/adviser/developers_guide.html#scheduling-workload-in-the-cluster

**Comment by pacospace** [comment]
> Can we create a new workflow that would encapsulate solvers and all the other data aggregation needed for a package (security indicators, ...)? The graph-refresh job can schedule just one workflow and argo can do all the remaining bits to have data aggregated (e.g. conditionally, retries, ...).

Yes sounds good to me. `package-learning` workflow. Where do we put this workflow? there should be a workflow task that decide if the SI workflow should run. Is it still triggered by graph-refresh-job?

**Comment by pacospace** [comment]
> Scheduling security indicators for already known packages can be performed using a simple script, even from a local machine:
> 
> https://thoth-station.ninja/docs/developers/adviser/developers_guide.html#scheduling-workload-in-the-cluster

But we have ~185k package releases to be analyzed for SI, we cannot schedule them all at once, graph-refresh-job allow to schedule 100 per hour at least.

**Comment by fridex** [comment]
> > Scheduling security indicators for already known packages can be performed using a simple script, even from a local machine:
> > https://thoth-station.ninja/docs/developers/adviser/developers_guide.html#scheduling-workload-in-the-cluster
> 
> But we have ~185k package releases to be analyzed for SI, we cannot schedule them all at once, graph-refresh-job allow to schedule 100 per hour at least.

It will be a one-time thing, we can spin up a one time job (in the worst case) with a script to take care of this for SI. Later, we should design a retry mechanism to retry only some of the `package-learning` workflow tasks.

**Comment by fridex** [comment]
> > > Scheduling security indicators for already known packages can be performed using a simple script, even from a local machine:
> > > https://thoth-station.ninja/docs/developers/adviser/developers_guide.html#scheduling-workload-in-the-cluster
> > 
> > 
> > But we have ~185k package releases to be analyzed for SI, we cannot schedule them all at once, graph-refresh-job allow to schedule 100 per hour at least.
> 
> It will be a one-time thing, we can spin up a one time job with a script to take care of this for SI. Later, we should design a retry mechanism to retry only some of the `package-learning` workflow tasks.

**Comment by pacospace** [comment]
> > > Scheduling security indicators for already known packages can be performed using a simple script, even from a local machine:
> > > https://thoth-station.ninja/docs/developers/adviser/developers_guide.html#scheduling-workload-in-the-cluster
> > 
> > 
> > But we have ~185k package releases to be analyzed for SI, we cannot schedule them all at once, graph-refresh-job allow to schedule 100 per hour at least.
> 
> It will be a one-time thing, we can spin up a one time job (in the worst case) with a script to take care of this for SI. Later, we should design a retry mechanism to retry only some of the `package-learning` workflow tasks.

As discussed today, we can use Kafka messages, what components produce these messages? graph-refresh-job again?

**Comment by pacospace** [comment]
This task will be performed by Thoth Investigator: after receiving a message that a package have been solved, it will decide if SI workflow need to be scheduled or not

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/investigator/pull/103

**Comment by pacospace** [comment]
Solved by :https://github.com/thoth-station/graph-refresh-job/pull/478 @saisankargochhayat

**Comment by pacospace** [comment]
https://github.com/thoth-station/investigator/issues/204
