### ISSUE TITLE
Make Graph Refresh Kafka Producer [8pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/graph-refresh-job#433]
As Thoth Investigator,
I want to receive messages from graph-refresh producer about packages Thoth needs to learn something about to keep knowledge fresh and updated.

Pre-requisite: 
- [x] Investigator is able to handle UnresolvedPackageMessage
- [x] Investigator is able to handle UnanalyzedPackageMessage
- [x] Investigator is able to handle UnresolvedPackageMessage

**Acceptance Criteria**

- [x] Modify logic and deployment of graph-refresh to be producer of messages;
- [x] Create query for unanalyzed packages from security point of view;
- [x] Create UnRevSolvedPackage in thoth-messaging
- [x] Create UnanalyzedPackageMessage in thoth-messaging for security
- [x] Add logic in graph-refresh to send messages: UnresolvedPackageMessage, UnanalyzedPackageMessage, UnRevSolvedPackage

**Comment by saisankargochhayat** [comment]
Todays discussion - 

- app.py needs to be converted to a producer.py
- remove all metrics apart from [_METRICS_INFO](https://github.com/thoth-station/graph-refresh-job/blob/fb80904296fc258d967d538bfdb07f7ec8de15b9/app.py#L61)
- The new app.py would be like - https://github.com/thoth-station/investigator/blob/master/producer.py
- Message contents would only have - package_name, package_version, index_url=sources, solver=solver

**Comment by pacospace** [comment]
> Todays discussion -
> 

* New UnrevsolvedPackageMessage with package_name, and package_version need to be created in thoth-messaging

> * app.py needs to be converted to a producer.py
> * remove all metrics apart from [_METRICS_INFO](https://github.com/thoth-station/graph-refresh-job/blob/fb80904296fc258d967d538bfdb07f7ec8de15b9/app.py#L61)
> * The new app.py would be like - https://github.com/thoth-station/investigator/blob/master/producer.py

UnresolvedPackageMessage in thoth-messaging: https://github.com/thoth-station/messaging/blob/master/thoth/messaging/unresolved_package.py
> * Message contents would only have - package_name, package_version, index_url=sources, solver=solver

**Comment by pacospace** [comment]
Solved by: https://github.com/thoth-station/graph-refresh-job/pull/478 @saisankargochhayat
