### ISSUE TITLE
Produce metrics from Argo CronWorkflow [8pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/graph-refresh-job#434]
As Thoth Developer,
I want to make sure messages and workflows work correctly and I want to evaluate SLI about the new architecture

Pre-requisite: 
- [x] graph-refresh is a Kafka Producer (https://github.com/thoth-station/graph-refresh-job/issues/433)

**Goal**

Have metrics to guarantee consistency in operations (e.g. 100 unresolved package message for solver-x-x-x sent -> 100 solvers for solver-x-x-x scheduled -> 100 solvers for solver-x-x-x solved -> etc..) 

2nd part: 
- [ ] Make graph-refresh an Argo CronWorkflow
- [ ] Define metrics created in Argo workflows

Reference:
- https://github.com/orgs/thoth-station/projects/5#card-40599061

**Comment by fridex** [comment]
Handled in https://github.com/thoth-station/thoth-application/issues/654
