### ISSUE TITLE
Discussing UnanalyzedPackageMessage

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/graph-refresh-job#457]
As mentioned, in #433, after discussing with @pacospace one approach suggested was, 
Create and query in storages, that would look for all solved packages, and check if they exist in `si_aggregated_run` table and if it doesn't exist there, we should produce messages to schedule SI workflows. 

Few concerns are the database query might be compute intensive, and also if the SI_workflows are already scheduled and currently in progress, for these packages, we might resend messages for those packages if graph-refresh-job is run. 
Also as Francesco mentioned, investigator already runs SI work-flows for all unresolved packages, if SI hasn't been run already, so also should we do this? @fridex

**Comment by fridex** [comment]
> As mentioned, in #433, after discussing with @pacospace one approach suggested was,
> Create and query in storages, that would look for all solved packages, and check if they exist in `si_aggregated_run` table and if it doesn't exist there, we should produce messages to schedule SI workflows.

We have already discussed this - yes, this is the way to go.

> Few concerns are the database query might be compute intensive, and also if the SI_workflows are already scheduled and currently in progress, for these packages, we might resend messages for those packages if graph-refresh-job is run.

Exactly, this query is computationally extensive, hence it should be done on the cronjob side. We need to have such query so it needs to happen somewhere (there are hundreds of thousands entries to go through). If we would do it on the investigator side, we would experience timeouts.

Regarding resending messages - we are in a distributed environment so these things can happen from time to time with this design (analyzing some multiple times) and I think we are fine with it. To restrict this, investigator should be the "gatekeeper" - when it receives the message, it should check if there is an SI workflow result (regardless of message producer), if not, it can schedule SI workflow (even though there is one already running). This query is much less computational intensive in comparision to the one checking for which packages we do not have SI workflows.

> Also as Francesco mentioned, investigator already runs SI work-flows for all unresolved packages, if SI hasn't been run already, so also should we do this? @fridex

Yes, see the paragraph above.
