### ISSUE TITLE
Question: should we remove limit for graph-refresh messages sent?

### ISSUE THREAD

**Issue by pacospace** [thoth-station/graph-refresh-job#469]
Currenly graph-refresh number of messages sent is fixed by the query https://github.com/thoth-station/graph-refresh-job/blob/fe4f6385cc0bd3fb395f97d3df7dde22de4d6fda/producer.py#L85, because there is pagination limit default set to 100 in storages: https://github.com/thoth-station/storages/blob/b82b5647c4e34210348335274f0149190781a4c3/thoth/storages/graph/postgres.py#L1511, therefore we are automatically limiting the learning rate as well.

Question: should we remove limit for graph-refresh messages sent? as we wanted to remove any constraint from graph-refresh producer side and investigator would handle the number of messages consumed.

**Comment by fridex** [comment]
I would keep this configurable for now on graph-refresh side and not rely on defaults on thoth-storages side - the `count` parameter could be supplied via env variables so we do not need to rebuild the container image each time we want to adjust it (also provide some sane default signalizing no limit, like `0`). It can happen that graph-refresh can spin up too often and produce messages that cannot be processed by the investigator in a reasonable time - hence investigator will schedule duplicate workflows.

Long-term we can try to setup kafka to perform deduplication of such messages.

**Comment by pacospace** [comment]
> I would keep this configurable for now on graph-refresh side and not rely on defaults on thoth-storages side - the `count` parameter could be supplied via env variables so we do not need to rebuild the container image each time we want to adjust it (also provide some sane default signalizing no limit, like `0`). It can happen that graph-refresh can spin up too often and produce messages that cannot be processed by the investigator in a reasonable time - hence investigator will schedule duplicate workflows.
> 
> Long-term we can try to setup kafka to perform deduplication of such messages.

Thanks! I opened this: https://github.com/thoth-station/graph-refresh-job/issues/473
