### ISSUE TITLE
Add ability to skip solver/revsolver scheduling

### ISSUE THREAD

**Issue by fridex** [thoth-station/graph-refresh-job#488]
**Is your feature request related to a problem? Please describe.**

To speed up the initial ingestion of packages, it would be great to introduce conditional scheduling of solver/revsolvers.

**Describe the solution you'd like**

For initial ingestion, we could turn off revsolvers so that we ingest data much faster. This is acceptable considering we turn on package-update job later on that will trigger revsolver workflows that are needed to correctly maintain dependencies in the database.

Once the initial ingestion is done, the revsolver scheduling can be turned on again.

**Describe alternatives you've considered**

Keep ingestion as is, which is slow.

**Additional context**

Introduce new environment variables `THOTH_GRAPH_REFRESH_NO_SOLVER` and `THOTH_GRAPH_REFRESH_NO_REVSOLVER` that would conditionally turn on/off solver/revsolver workflows (messages sent).

**Comment by fridex** [comment]
CC @saisankargochhayat @pacospace

**Comment by pacospace** [comment]
what about `THOTH_GRAPH_REFRESH_NO_SECURITY`?

**Comment by fridex** [comment]
> what about `THOTH_GRAPH_REFRESH_NO_SECURITY`?

Yes, we can add it as well. All the workflows this component schedules so we can adjust behavior accordingly.

**Comment by pacospace** [comment]
> > what about `THOTH_GRAPH_REFRESH_NO_SECURITY`?
> 
> Yes, we can add it as well. All the workflows this component schedules so we can adjust behavior accordingly.

Thanks! very useful feature :100:
